import { Metadata } from 'next'
import Header from '../../components/Header'
import Breadcrumbs from '../../components/Breadcrumbs'
import Footer from '../../components/Footer'

export const metadata: Metadata = {
    title: 'Privacy Policy - Thin Air',
    description: 'How we handle your data. Short version: We delete it after 30 days.',
}

export default function PrivacyPage() {
    return (
        <main className="min-h-screen bg-white dark:bg-gray-900 text-gray-900 dark:text-white">
            <Header />
            <Breadcrumbs items={[{ label: 'Privacy Policy' }]} />

            <section className="py-20 px-4">
                <div className="max-w-4xl mx-auto prose dark:prose-invert">
                    <h1 className="text-4xl font-bold mb-8">Privacy Policy</h1>
                    <p className="text-lg mb-8">Last updated: November 26, 2025</p>

                    <h2>1. The Short Version</h2>
                    <p>
                        We collect the minimum amount of data needed to provide our service. We use AI to process your inputs. We delete your generated application data after 30 days. We don't sell your data.
                    </p>

                    <h2>2. Information We Collect</h2>
                    <ul>
                        <li><strong>Account Info:</strong> Name, email, and password (encrypted).</li>
                        <li><strong>Input Data:</strong> Voice notes, text descriptions, and files you upload to describe your app idea.</li>
                        <li><strong>Generated Data:</strong> The code, database schemas, and assets generated by our AI for your application.</li>
                    </ul>

                    <h2>3. How We Use Your Data</h2>
                    <ul>
                        <li>To provide the Thin Air service and generate your application.</li>
                        <li>To process payments (via secure third-party providers like Stripe).</li>
                        <li>To communicate with you about your project status.</li>
                    </ul>
                    <p>
                        <strong>AI Processing:</strong> Your input data is processed by AI models (e.g., Google Gemini) to generate your software. By using our service, you consent to this processing.
                    </p>

                    <h2>4. Data Retention (The 30-Day Rule)</h2>
                    <p>
                        We enforce a strict data retention policy for your generated applications:
                    </p>
                    <ul>
                        <li><strong>Application Data:</strong> All code, databases, and assets generated for your project are <strong>automatically deleted 30 days</strong> after creation.</li>
                        <li><strong>Account Data:</strong> We keep your account information (email, credit balance, transaction history) indefinitely so you can return to build more apps, unless you ask us to delete it.</li>
                    </ul>

                    <h2>5. Data Sharing</h2>
                    <p>
                        We do not sell your personal data. We only share data with:
                    </p>
                    <ul>
                        <li><strong>Service Providers:</strong> Hosting providers (to run the app temporarily), AI providers (to generate the code), and payment processors.</li>
                        <li><strong>Legal Requirements:</strong> If required by law enforcement.</li>
                    </ul>

                    <h2>6. Security</h2>
                    <p>
                        We use industry-standard encryption for data in transit and at rest. However, no method of transmission over the internet is 100% secure.
                    </p>

                    <h2>7. Contact Us</h2>
                    <p>
                        If you have questions about your data, contact <a href="mailto:support@almostmagic.net.au">support@almostmagic.net.au</a>.
                    </p>
                </div>
            </section>

            <Footer />
        </main>
    )
}
